okwasniewski/MiniSim

- MiniSim.xcodeproj/project.pbxproj
- MiniSim/AndroidSubMenuItem.swift
- MiniSim/DeviceMenuItem.swift
- MiniSim/Extensions/Pasteboard+utils.swift
- MiniSim/Menu.swift
- MiniSim/Service/Adb.swift
- MiniSim/Service/DeviceService.swift
> feat: allow users to copy adb id and device name on Android

- MiniSim.xcodeproj/project.pbxproj
- MiniSim.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- MiniSim/Info.plist
- MiniSim/MiniSimRelease.entitlements
- MiniSim/Views/About.swift
- appcast.xml
> feat: add auto update experience

- appcast.xml
This PR fixes the release version in appcast.
> fix: release version

- MiniSim/Menu.swift
- MiniSim/MenuItems/AndroidSubMenuItem.swift
- MiniSim/MiniSim.swift
- MiniSim/Model/Device.swift
- MiniSim/Service/Adb.swift
- MiniSim/Service/DeviceService.swift
The goal of this PR is to refactor completion handlers to synchronous code. 
Features: 
- Fetch devices on the menu open, allowing them to sync every time.
Fixes:
- #26 
- Fix attaching android devices after clearing cache
> feat: refactor completion handlers, update devices on open

- MiniSim/AccessibilityElement.swift
- MiniSim/Menu.swift
- MiniSim/Service/DeviceService.swift
- MiniSim/Views/About.swift
- MiniSim/Views/Preferences.swift
Simulator.app has this weird behaviour that simulator sometimes appears as open but Simulator.app is not running. This PR addresses that issue and checks if it's runnning.
> Fix launching iOS Simulators

- MiniSim/Menu.swift
> feat: display notifications when copying text

- MiniSim.xcodeproj/project.pbxproj
- MiniSim/AppDelegate.swift
- MiniSim/Extensions/PaneIdentifier.swift
- MiniSim/Extensions/UserDefaults+Configuration.swift
- MiniSim/Menu.swift
- MiniSim/MiniSim.swift
- MiniSim/Model/Parameter.swift
- MiniSim/Service/DeviceService.swift
- MiniSim/Views/Devices.swift
- MiniSim/Views/ParametersTable.swift
> feat: allow to pass additional custom params

- MiniSim.xcodeproj/project.pbxproj
- MiniSim/Extensions/NSNotificationName.swift
- MiniSim/Extensions/UserDefaults+Configuration.swift
- MiniSim/Menu.swift
- MiniSim/MiniSim.swift
- MiniSim/Onboarding.swift
- MiniSim/Service/Adb.swift
- MiniSim/Service/AndroidHomeError.swift
- MiniSim/Service/DeviceService.swift
- MiniSim/Views/Onboarding/AndroidPathInput.swift
- MiniSim/Views/Onboarding/BlurredView.swift
- MiniSim/Views/Onboarding/OnboardingButton.swift
- MiniSim/Views/Onboarding/OnboardingItem.swift
- MiniSim/Views/Onboarding/OnboardingPager.swift
- MiniSim/Views/Onboarding/PermissionsView.swift
- MiniSim/Views/Onboarding/ReadyPopOver.swift
- MiniSim/Views/Onboarding/SetupView.swift
- MiniSim/Views/Onboarding/WelcomeView.swift
- MiniSim/Views/Preferences.swift
- MiniSim/Views/ViewModifiers.swift
Goal of this PR is to create an onboarding experience
> feat: create onboarding experience

- MiniSim.xcodeproj/project.pbxproj
- MiniSim/Extensions/UNUserNotificationCenter+showNotification.swift
- MiniSim/Menu.swift
- MiniSim/MenuItems/MenuSections.swift
- MiniSim/MiniSim.swift
- MiniSim/Service/DeviceService.swift
Goal of this PR is to add option to clear Xcode derived data.
> feat: add option to clear derived data

- MiniSim/Menu.swift
- MiniSim/MiniSim.swift
- MiniSim/Model/Command.swift
- MiniSim/Service/DeviceService.swift
- MiniSim/Views/CustomCommands/CustomCommandForm.swift
- MiniSim/Views/CustomCommands/CustomCommandFormViewModel.swift
Goal of this PR is to add option for custom commands to boot devices for both platforms.
> feat: allow custom commands to boot devices

- MiniSim/AccessibilityElement.swift
- MiniSim/Menu.swift
- MiniSim/MiniSim.swift
Update quality of service to execute tasks with higher priority under heavy load.
> fix: update quality of service

- README.md
- docs/custom_commands.md
This PR adds custom commands documentation.
Closes: #68
> docs: add custom commands documentation

- MiniSim/MenuItems/MenuSections.swift
This PR introduces MacOS Sonoma section titles
> feat: use MacOS Sonoma section titles

- .github/workflows/swiftlint.yml
> feat: add swiftlint CI step

- MiniSim/Extensions/NSMenuItem+ConvenienceInit.swift
This PR fixes custom commands not executing because of missing tag
> fix: custom commands not executing

- MiniSim/Extensions/UserDefaults+Configuration.swift
- MiniSim/Service/Terminal/TerminalApps.swift
- MiniSim/Views/Preferences.swift
This pull request add a new feature to the preference tab, which allows user to change the preferred terminal of their choice.
closes #112
[added] - added new picker for selecting terminal from the list of supported terminal
> UI for selecting preferred terminal

- MiniSim.xcodeproj/project.pbxproj
- MiniSim/Extensions/Thread+Asserts.swift
- MiniSim/MainMenu.xib
- MiniSim/Service/DeviceService.swift
This PR asserts background thread when launching custom commands and simulators using additional options, it should fix app freezing.
Fix background thread usage that sometimes caused app freeze
Test if thread asserts won't crash the app
> fix: assert threads to prevent app freezing

- MiniSim.xcodeproj/project.pbxproj
- MiniSim.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- MiniSim/Extensions/PaneIdentifier.swift
- MiniSim/MiniSim.swift
- MiniSim/Views/Devices.swift
- MiniSim/Views/Preferences.swift
This PR bumps packages
feat: bump packages
CI Green
> feat: bump packages

- MiniSim.xcodeproj/project.pbxproj
- MiniSim/Service/DeviceParser.swift
- MiniSim/Service/DeviceService.swift
- MiniSimTests/DeviceParserTests.swift
This PR implements Device Parser + tests.
feat: implement device parser tests
CI Green
> feat: implement device parser tests

- MiniSim/Service/DeviceParser.swift
- MiniSim/Views/Preferences.swift
This PR includes some minor UI and logic fixes 
fix: Don't show unpaired devices
fix: Use proper initializer for Image
CI Green
> fix: minor ui fixes
